#!/usr/bin/env bash

node types/transform_schema.js

node_modules/.bin/quicktype \
  -o src/tau_types.ts \
  --lang typescript \
  --src-lang schema \
  --no-runtime-typecheck \
  --just-types \
  --prefer-unions \
  --acronym-style camel \
  './types/schema_fixed.json#/definitions/'

OUT_FILE="./src/tau_types.ts"
echo >> "$OUT_FILE"
echo "export type EventTypeMap = {" >> "$OUT_FILE"
jq -r \
  '.definitions | keys | .[]' \
  types/schema_fixed.json \
  | sed -e 's/\./\-/g;p;s/[-_]/\./g;s/\b\(.\)/\u\1/g;s/\.//g' \
  | paste -s -d' \n' \
  | sed 's/\([-a-z_]*\)\(.*\)/"\1":\2,/' >> "$OUT_FILE"
echo "};" >> "$OUT_FILE"
